
[font]
size = 20
#vim tab swaps
[keyboard]
bindings = [
  { key = "ArrowRight", mods = "Command|Alt", action = "SelectNextTab" },
  { key = "ArrowLeft", mods = "Command|Alt", action = "SelectPreviousTab" },
]
[window]
option_as_alt = "OnlyLeft"

[general]
# Sam's Alacritty file
live_config_reload = true
import = ["~/.config/alacritty/themes/themes/nord.toml"]
