[user]
name = "Samuel S. Guyah"
email = "septimusguy@gmail.com"

[signing]
behavior = "own"
backend = "ssh"
key = "/Users/mecha/.ssh/id_ed25519_jj_signing.pub"

[git]
sign-on-push = true

[ui]
editor = "hx"

[aliases]
cm = ["commit", "-m"]
adv = ["bookmark", "advance", "main", "--to", "@-"]
pub = ["git", "push"]
