[user]
name = "Samuel S. Guyah"
email = "septimusguy@gmail.com"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519_jj_signing.pub"

[[--scope]]
--when.hostnames = ["CW-KWW5GWG2VF-L"]

[--scope.signing]
backend = "gpg"
key = "5007E02944916AE2"

[git]
sign-on-push = true

[ui]
editor = "hx"
diff-formatter = "delta"

[colors]
"diff added"       = { fg = "#448420" }
"diff added token" = { fg = "#448420" }

[merge-tools.delta]
program = "delta"
diff-args = [
  "--color-only",
  "--light",
  "--syntax-theme=none",
  "--plus-style", "black #e4f2dc",
  "--plus-non-emph-style", "black #e4f2dc",
  "--plus-emph-style", "black #cfe7c4",
  "--plus-empty-line-marker-style", "black #e4f2dc",
  "$left",
  "$right",
]
diff-expected-exit-codes = [0, 1]

[aliases]
cm = ["commit", "-m"]
adv = ["bookmark", "advance", "main", "--to", "@-"]
pub = ["git", "push"]
