[user]
name = "Samuel S. Guyah"
email = "sguyah@coreweave.com"

[signing]
behavior = "own"
backend = "gpg"
key = "5007E02944916AE2"

[git]
sign-on-push = true

[ui]
editor = "hx"
diff-formatter = "delta"

[colors]
"diff added"       = { fg = "#448420" }
"diff added token" = { fg = "#448420" }

[merge-tools.delta]
program = "sh"
diff-args = ["-c", "exec \"$HOME/.config/bin/delta-auto\" \"$@\"", "delta-auto", "--color-only", "$left", "$right"]
diff-expected-exit-codes = [0, 1]

[aliases]
cm = ["commit", "-m"]
adv = ["bookmark", "advance", "main", "--to", "@-"]
pub = ["git", "push"]
