theme = "catppuccin_latte"


[keys.normal.space]
# yazi
z = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]



[editor]
# What does this do?
bufferline = "multiple"

# Lines so i dont kill myself over python
indent-guides.render = true

# BEGIN HACK TO TURN ON INLINE DIAGNOTICS
# Not sure if I really need this. But we will see.
#line-number = "relative"

# Hopefully this can be deleted soon when diagnostics are turned on
# 
# Minimum severity to show a diagnostic after the end of a line:
end-of-line-diagnostics = "hint"

# Hopefully this can be deleted too.
[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "hint"
# Minimum severity to show a diagnostic on other lines: kinda annoying when working with new code
# other-lines = "hint"
# END HACK

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
