[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true


[language-server.rust-analyzer.config.check]
command = "clippy"
features = "all"
