[[language]]
name = "tsx"
#formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "rust"
auto-format = true
[language-server.rust-analyzer.config.check]
command = "clippy"
features = "all"

[[language]]
name = "python"
language-servers = ["ruff"]
auto-format = true
[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "markdown"
language-servers = [{ name = 'ltex' }]
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true

[language-server.ltex]
command = "/Users/mecha/.local/ltex-ls-16.0.0/bin/ltex-ls"
