# Author: ChiefMateStarbuck <septimusguy@gmail.com>

"attribute"                       = { modifiers = ["italic"] }

"diagnostic"                      = { underline = { style = "curl" } }
"diagnostic.hint"                 = { underline = { style = "curl" } }
"diagnostic.warning"              = { underline = { style = "curl" } }
"diagnostic.error"                = { underline = { style = "curl" } }
"diagnostic.info"                 = { underline = { style = "curl" } }
"diagnostic.unnecessary"          = { modifiers = ["dim"] }
"diagnostic.deprecated"           = { modifiers = ["crossed_out"] }

"keyword.storage.type"            = { modifiers = ["italic"] }

"markup.bold"                     = { modifiers = ["bold"] }
"markup.heading"                  = { modifiers = ["bold"] }
"markup.italic"                   = { modifiers = ["italic"] }
"markup.quote"                    = { modifiers = ["italic"] }
"markup.strikethrough"            = { modifiers = ["crossed_out"] }

"type"                            = { modifiers = ["italic"] }
"type.enum.variant"               = { modifiers = ["italic"] }

"ui.background"                   = { bg = "background" }
"ui.text"                         = { fg = "foreground" }
"ui.text.focus"                   = { fg = "foreground" }
"ui.cursor"                       = { bg = "primary", modifiers = ["dim"] }
"ui.cursor.insert"                = { fg = "primary", bg  = "secondary", modifiers  = ["dim"] }
"ui.cursor.match"                 = { fg = "primary", bg  = "secondary" }
"ui.cursor.normal"                = { fg = "primary", bg  = "secondary", modifiers = ["dim"] }
"ui.cursor.select"                = { fg = "primary", bg  = "secondary", modifiers = ["dim"] }
"ui.cursor.primary.insert"        = { fg = "background", bg = "foreground" }
"ui.cursor.primary.normal"        = { fg = "background", bg = "foreground" }
"ui.cursor.primary.select"        = { fg = "background", bg = "foreground" }
"ui.cursorline.primary"           = { bg = "primary" }
"ui.menu.selected"                = { modifiers = ["dim"] }
"ui.selection"                    = { bg = "secondary", underline = { style = "curl" } }
"ui.selection.primary"            = { bg = "primary", underline = { style = "curl" }}
"ui.statusline"                   = { fg = "background", bg = "foreground" }
"ui.statusline.inactive"          = { bg = "background" }
"ui.statusline.insert"            = {  modifiers = ["bold"] }
"ui.statusline.normal"            = {  modifiers = ["bold"] }
"ui.statusline.select"            = {  modifiers = ["bold"] }
"ui.bufferline"                   = { fg = "background", bg = "foreground"}
"ui.bufferline.active"            = { bg = "background"}
"ui.virtual.inlay-hint.parameter" = { modifiers = ["italic", "dim"] }
"ui.virtual.inlay-hint.type"      = { modifiers = ["italic", "dim"] }
"ui.virtual.jump-label"           = { modifiers = ["bold"] }

"variable.builtin"                = { modifiers = ["bold"] }
"variable.parameter"              = { modifiers = ["bold"] }

[palette]
foreground = "#ffffff"
background = "#000000"
primary    = "#bababa"
secondary  = "#555555"
