# Author : Samuel Guyah <septimusguy@gmail.com>

"ui.selection" = { fg = "black", bg = "selection" }
"ui.cursor" = { fg = "black", bg = "light-gray" }
"ui.cursor.primary" = { fg = "black", bg = "light-gray" }
"ui.cursor.match" = { modifiers = ["underlined"] }
"ui.background.separator" = "gray"
"ui.linenr" = "gray"
"ui.linenr.selected" = { fg = "black", bg = "selection" }
"ui.statusline" = { bg = "black", fg = "white" }
"ui.menu" = { fg = "white", bg = "black" }
"ui.menu.selected" = { bg = "light-gray", fg = "black" }
"ui.popup" = { fg = "white", bg = "black" }
"ui.help" = { fg = "white", bg = "black" }
"ui.virtual.ruler" = { underline = { style = "line" } }
"ui.bufferline" = { fg = "white", bg = "black" }
"ui.bufferline.active" = { fg = "black", bg = "white" }
"ui.bufferline.background" = { bg = "black" }

"attribute" = { fg = "black" }
"comment" = { bg = "soft-purple", fg = "black" }
"constant" = { fg = "black" }
"keyword" = { fg = "black" }
"string" = { bg = "soft-green", fg = "black" }
"type" = { fg = "black" }

"diff.plus" = { fg = "black", bg = "soft-green" }
"diff.minus" = { fg = "black", bg = "soft-red" }
"diff.delta" = { fg = "black", bg = "soft-blue" }

"warning" = { fg = "black", bg = "soft-yellow" }
"error" = { fg = "black", bg = "soft-red" }
"hint" = { fg = "black", bg = "soft-blue" }

"diagnostic.warning" = { fg = "black", bg = "soft-yellow" }
"diagnostic.error" = { fg = "black", bg = "soft-red" }
"diagnostic.hint" = { fg = "black", bg = "soft-blue" }
"diagnostic.info" = { fg = "black", bg = "soft-purple" }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

[palette]
soft-green = "#e4f2dc"
soft-purple = "#eadff0"
soft-blue = "#dceaf6"
soft-apricot = "#f3e3d3"
soft-yellow = "#f4edcf"
soft-red = "#f2d8d5"
selection = "#e3e1e1"
