# Author :ChiefMateStarbuck <septimusguy@gmail.com>

"annotation"                      = { fg = "black"                                                     }

"attribute"                       = { fg = "black",              modifiers = ["italic"]                     }

"comment"                         = { fg = "black"                                                        }
"comment.block"                   = { fg = "black"                                                        }
"comment.block.documentation"     = { fg = "black"                                                        }
"comment.line"                    = { fg = "black"                                                        }

"constant"                        = { fg = "black"                                                         }
"constant.builtin"                = { fg = "black"                                                         }
"constant.builtin.boolean"        = { fg = "black"                                                         }
"constant.character"              = { fg = "black"                                                           }
"constant.character.escape"       = { fg = "black"                                                           }
"constant.macro"                  = { fg = "black"                                                         }
"constant.numeric"                = { fg = "black"                                                         }
"constructor"                     = { fg = "black"                                                         }

"definition"                      = { underline = { color = "black"                                        } }
"diagnostic"                      = { underline = { color = "black",          style = "curl"             } }
"diagnostic.hint"                 = { underline = { color = "black",          style = "curl"             } }
"diagnostic.warning"              = { underline = { color = "black",          style = "curl"             } }
# clean up spacing
"diagnostic.error"                = { underline = { color = "black",             style = "curl"             } }
"diagnostic.info"                 = { underline = { color = "black",            style = "curl"             } }
"diagnostic.unnecessary"          = { modifiers = ["dim"]                                                   }
"diagnostic.deprecated"           = { modifiers = ["crossed_out"]                                           }

"error"                           = { fg    = "black"                                                         }
"hint"                            = { fg    = "black"                                                      }
"info"                            = { fg    = "black"                                                        }
"warning"                         = { fg    = "black"                                                      }

"diff.delta"                      = { fg    = "black"                                                      }
"diff.minus"                      = { fg    = "black"                                                         }
"diff.plus"                       = { fg    = "black"                                                       }

# d
"function"                        = { fg = "black"                                                          }
"function.builtin"                = { fg = "black"                                                          }
"function.call"                   = { fg = "black"                                                          }
"function.macro"                  = { fg = "black"                                                         }
"function.method"                 = { fg = "black"                                                          }

"keyword"                         = { fg = "black"                                                           }
"keyword.control.conditional"     = { fg = "black"                                                           }
"keyword.control.exception"       = { fg = "black"                                                         }
"keyword.control.import"          = { fg = "black"                                                           }
"keyword.control.repeat"          = { fg = "black"                                                           }
"keyword.directive"               = { fg = "black"                                                          }
"keyword.function"                = { fg = "black"                                                           }
"keyword.operator"                = { fg = "black"                                                           }
"keyword.return"                  = { fg = "black"                                                           }
"keyword.storage"                 = { fg = "black"                                                           }
"keyword.storage.modifier"        = { fg = "black"                                                           }
"keyword.storage.type"            = { fg = "black",               modifiers = ["italic"]                     }

"label"                           = { fg = "black"                                                           }

"markup.bold"                     = { fg    = "black",          modifiers = ["bold"]                       }
"markup.heading"                  = { fg    = "black",          modifiers = ["bold"]                       }
"markup.italic"                   = { fg    = "black",          modifiers = ["italic"]                     }
"markup.link.text"                = { fg    = "black"                                                        }
"markup.link.url"                 = { fg    = "black"                                                        }
"markup.list"                     = { fg    = "black"                                                        }
"markup.quote"                    = { fg    = "black",          modifiers = ["italic"]                     }
"markup.raw"                      = { fg    = "black"                                                  }
"markup.strikethrough"            = {                            modifiers = ["crossed_out"]                }

"punctuation"                     = { fg = "black"                                                     }
"punctuation.bracket"             = { fg = "black"                                                     }
"punctuation.delimiter"           = { fg = "black"                                                     }
"punctuation.special"             = { fg = "black"                                                           }

"special"                         = { fg = "black"                                                           }

"string"                          = { fg = "black"                                                         }
"string.regexp"                   = { fg = "black"                                                            }
"string.special"                  = { fg = "black"                                                         }
"string.symbol"                   = { fg = "black"                                                         }

"tag"                             = { fg = "black"                                                           }
"tag.attribute"                   = { fg = "black"                                                         }
"tag.delimiter"                   = { fg = "black"                                                     }

"type"                            = { fg = "black",               modifiers = ["italic"]                     }
"type.builtin"                    = { fg = "black"                                                           }
"type.enum.variant"               = { fg = "black",         modifiers = ["italic"]                     }

"ui.background"                   = { fg    = "black",      bg = "white"                          }
#work on cursor colors becaus highlighting is very dark
"ui.cursor"                       = { fg    = "white",      bg = "grey",        modifiers = ["dim"]  }
"ui.cursor.insert"                = { fg    = "black",      bg = "grey",         modifiers = ["dim"]  }	
"ui.cursor.match"                 = { fg    = "black",      bg = "grey"                                }
"ui.cursor.normal"                = { fg    = "black",      bg = "grey",        modifiers = ["dim"]  }	
# how to make selecting not as dark?
"ui.cursor.select"                = { fg    = "black",      bg = "grey",        modifiers = ["dim"]  }	
# differentiate primary from others
"ui.cursor.primary.insert"        = { fg    = "black",      bg = "grey"                               }	
"ui.cursor.primary.normal"        = { fg    = "black",      bg = "grey"                              }	
"ui.cursor.primary.select"        = { fg    = "black",      bg = "grey"                                }
"ui.cursorline.primary"           = {                            bg = "grey"                          }
"ui.debug"                        = { fg    = "black"                                                         }
"ui.help"                         = { fg    = "black",      bg = "white"                               }
"ui.highlight.frameline"          = { fg    = "black",      bg = "white"                                 }
"ui.linenr"                       = { fg    = "black"                                                     }
"ui.linenr.selected"              = { fg    = "black"                                                  }
"ui.menu"                         = { fg    = "black",      bg = "white"                        }
"ui.menu.scroll"                  = { fg    = "black",      bg = "white"                        }
"ui.menu.selected"                = { fg    = "black",    bg = "white",        modifiers = ["dim"]  }
"ui.popup"                        = { fg    = "black",      bg = "white"                               }
#decide what to do with these two lines and how to reverse?
"ui.selection"                    = {                            bg = "selection"                           }
"ui.selection.primary"            = {                            bg = "current_line"                        }

"ui.statusline"                   = { fg    = "black",      bg = "white"                              }
"ui.statusline.inactive"          = { fg    = "black",         bg = "white"                              }
"ui.statusline.insert"            = { fg    = "black",           bg = "white",         modifiers = ["bold"] }
"ui.statusline.normal"            = { fg    = "black",           bg = "white",        modifiers = ["bold"] }
"ui.statusline.select"            = { fg    = "black",           bg = "white",          modifiers = ["bold"] }
"ui.text"                         = { fg    = "black"                                                  }
"ui.text.focus"                   = { fg    = "black"                                                        }
"ui.virtual.indent-guide"         = { fg    = "indent"                                                      }
"ui.virtual.inlay-hint"           = { fg    = "cyan"                                                        }
"ui.virtual.inlay-hint.parameter" = { fg    = "cyan",            modifiers = ["italic", "dim"]              }
"ui.virtual.inlay-hint.type"      = { fg    = "cyan",            modifiers = ["italic", "dim"]              }
"ui.virtual.jump-label"           = { fg    = "pink",            modifiers = ["bold"]                       }
"ui.virtual.ruler"                = { bg    = "black"                                                       }
"ui.virtual.whitespace"           = { fg    = "whitespace"                                                  }
"ui.virtual.wrap"                 = { fg    = "current_line"                                                }
"ui.window"                       = { fg    = "foreground"                                                  }

"variable"                        = { fg = "black"                                                     }
"variable.builtin"                = { fg = "black",             modifiers = ["bold"]                     }
"variable.other"                  = { fg = "black"                                                     }
"variable.other.member"           = { fg = "black"                                                     }
"variable.parameter"              = { fg = "black",             modifiers = ["bold"]                     }


[palette]
black             = "#000000"
grey              = "#cccccc"
white             = "#ffffff" 
background        = "#282A36"
comment           = "#6272A4"
current_line      = "#44475a"
cursorline        = "#2d303e"
cyan              = "#8be9fd"
darker            = "#222430"
foreground        = "#f8f8f2"
green             = "#50fa7b" 
indent            = "#56596a"
orange            = "#ffb86c" 
pink              = "#ff79c6"
purple            = "#BD93F9" 
red               = "#ff5555"
selection         = "#363848"
whitespace        = "#586693"
yellow            = "#f1fa8c" 
